import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const promptsDir = join(root, 'prompts');
const outputPath = join(root, 'src', 'generated', 'prompts.ts');
const promptNames = ['system', 'company', 'sales', 'qualification', 'memory', 'handoff', 'safety'];

const entries = await Promise.all(
  promptNames.map(async (name) => [name, await readFile(join(promptsDir, `${name}.md`), 'utf8')])
);

const promptObject = entries
  .map(([name, value], index) => {
    const comma = index === entries.length - 1 ? '' : ',';
    return `  ${name}:\n    ${quoteTsString(value)}${comma}`;
  })
  .join('\n');

const moduleSource = `// AUTO-GENERATED - DO NOT EDIT DIRECTLY
// Generated by scripts/build-prompts.mjs from prompts/*.md.

export const prompts = {
${promptObject}
} as const;

export type PromptName = keyof typeof prompts;
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, moduleSource);

function quoteTsString(value) {
  const quote = value.includes("'") ? '"' : "'";
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(new RegExp(quote, 'g'), `\\${quote}`)
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n');
  return `${quote}${escaped}${quote}`;
}
